version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /run/user/1000/pulse:/run/user/1000/pulse  # PulseAudio socket
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie  # PulseAudio cookie
      - /dev/dri:/dev/dri  # GPU access
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PULSE_COOKIE=/root/.config/pulse/cookie
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri  # GPU device
    group_add:
      - audio
      - video  # Required for GPU access
    restart: unless-stopped
